In [177]:
# importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## **Loading, Understanding the data**

In [178]:
df = pd.read_csv("/kaggle/input/datasets/juhibhojani/house-price/house_prices.csv")
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [179]:
df.shape

(187531, 21)

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [181]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [182]:
print("num of duplicate rows:", df.duplicated().sum())

num of duplicate rows: 0

In [183]:
# seperate the numerical and categorical columns
df_cat = df.select_dtypes(['object'])
df_num = df.select_dtypes(['int64', 'float64'])

In [184]:
df_cat.describe()

,Title,Description,Amount(in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
count,187531,184508,187531,187531,106858,186916,180454,187448,184634,117298,106095,77853,186703,138596,84174,122014,79846
unique,32446,65634,1561,81,2758,1,947,4,3,8,19,10376,11,11,229,4,2976
top,2 BHK Ready to Occupy Flat for sale in Divyasr...,Multistorey apartment is available for sale. I...,Call for Price,new-delhi,1000 sqft,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Main Road,Hamdam Apartment,2,2,1 Covered,Freehold,1100 sqft
freq,2106,2732,9684,27599,5285,186916,12433,144172,88318,54741,32193,1648,93007,51809,38754,112229,2599

In [185]:
df_num.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
10%     18753.000000       3.434000e+03         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
90%    168777.000000       1.271400e+04         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

## **Data Preprocessing**

### **Renaming Columns**

In [186]:
df.rename(columns={
    'index': 'Index',
    'Amount(in rupees)': 'Amount',
    'Price (in rupees)': 'Price',
    'location': 'Location',
    'facing': 'Facing',
    'overlooking': 'Overlooking'
}, inplace=True)

df.rename(columns={col: col.replace(' ', '') for col in df.columns}, inplace=True)
df.head(2)

,Index,Title,Description,Amount,Price,Location,CarpetArea,Status,Floor,Transaction,...,Facing,Overlooking,Society,Bathroom,Balcony,CarParking,Ownership,SuperArea,Dimensions,PlotArea
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN

### **Handling Missing Data**

In [187]:
# droping non-essential columns
df.drop(['Index', 'Title', 'Description', 'Price', 'Society', 'Dimensions'], axis=1, inplace=True)

In [188]:
# check number of null values
df.isnull().sum().sort_values(ascending=False)

PlotArea       187531
SuperArea      107685
CarParking     103357
Overlooking     81436
CarpetArea      80673
Facing          70233
Ownership       65517
Balcony         48935
Floor            7077
Furnishing       2897
Bathroom          828
Status            615
Transaction        83
Amount              0
Location            0
dtype: int64

In [189]:
# drop null values from CarpetArea column
df.dropna(subset=['CarpetArea'], inplace=True)
df.shape

(106858, 15)

In [190]:
# drop columns PlotArea and SuperArea
df.drop(['PlotArea', 'SuperArea'], axis=1, inplace=True)

In [191]:
# fill null values in other columns
df['Bathroom'] = df['Bathroom'].fillna('0')
df['Balcony'] = df['Balcony'].fillna('0')
df['CarParking'] = df['CarParking'].fillna('0')

df['Overlooking'] = df['Overlooking'].fillna('Not Available')

df['Furnishing'] = df['Furnishing'].fillna(df['Furnishing'].mode()[0])
df['Status'] = df['Status'].fillna(df['Status'].mode()[0])
df['Transaction'] = df['Transaction'].fillna(df['Transaction'].mode()[0])

df['Floor'] = df['Floor'].fillna('0 out of 0')

df['Facing'] = df['Facing'].fillna('No data')
df['Ownership'] = df['Ownership'].fillna('No data')

In [192]:
df.reset_index(inplace=True)
df.drop('index', axis=1, inplace=True)

In [193]:
df.isnull().sum().sort_values(ascending=False)

Amount         0
Location       0
CarpetArea     0
Status         0
Floor          0
Transaction    0
Furnishing     0
Facing         0
Overlooking    0
Bathroom       0
Balcony        0
CarParking     0
Ownership      0
dtype: int64

### **Feature Engineering**

In [195]:
df.dtypes

Amount         object
Location       object
CarpetArea     object
Status         object
Floor          object
Transaction    object
Furnishing     object
Facing         object
Overlooking    object
Bathroom       object
Balcony        object
CarParking     object
Ownership      object
dtype: object

In [196]:
# removing certain records
df = df[df['Amount'] != 'Call for Price']
df = df[df['Floor'].str.count(' ') == 3]

df.reset_index(inplace=True)
df.drop('index', axis=1, inplace=True)

In [197]:
# handling Location column
df['Location'] = df['Location'].str.capitalize()

In [198]:
# handling Floor
df['Floor'] = df['Floor'].apply(lambda x: x.replace('Ground', '0').replace('Upper Basement', '-1').replace('Lower Basement', '-2').replace(' 0', ' 1'))

floor_splitted = df['Floor'].str.split(' ', expand=True)
house_floor = floor_splitted[0].astype(np.int64)
total_floors = floor_splitted[3].astype(np.int64)

df['Floor'] = house_floor / total_floors
df['TotalFloors'] = pd.Series(total_floors)

In [199]:
# handling Bathroom and Balcony
df['Bathroom'] = df['Bathroom'].replace('> 10', '11')
df['Balcony'] = df['Balcony'].replace('> 10', '11')

df['Bathroom'] = df['Bathroom'].astype(np.int64)
df['Balcony'] = df['Balcony'].astype(np.int64)

In [200]:
# handling CarParking
df['CarParking'] = df['CarParking'].str.split(' ', expand=True)[0].astype(np.int64)

In [201]:
# handling CarpetArea
df['CarpetArea'] = df['CarpetArea'].str.split(' ', expand=True)[0].astype(np.float64)

In [202]:
# handling Amount
amount_split = df['Amount'].str.split(' ', expand=True)
amount_lakhs = amount_split[0][amount_split[1] == 'Lac'].astype(np.float64)
amount_crores = amount_split[0][amount_split[1] == 'Cr'].astype(np.float64)

amount_temp = pd.Series(np.ones(df.shape[0], dtype=np.float64))
amount_temp.iloc[df[df['Amount'].str.endswith(' Lac ')].index] = amount_lakhs / 100
amount_temp.iloc[df[df['Amount'].str.endswith(' Cr ')].index] = amount_crores

df['Amount'] = amount_temp

In [203]:
# handling Overlooking
overlooking_dummies = df['Overlooking'].str.get_dummies(sep=', ')
overlooking_dummies = overlooking_dummies.add_prefix('Overlooking_')

overlooking_dummies.rename(columns={
    'Overlooking_Garden/Park': 'Overlooking_GardenPark',
    'Overlooking_Main Road': 'Overlooking_MainRoad',
    'Overlooking_Not Available': 'Overlooking_NotAvailable',
    'Overlooking_Pool': 'Overlooking_Pool'
}, inplace=True)

df = pd.concat([df, overlooking_dummies], axis=1)
df.drop('Overlooking', axis=1, inplace=True)

In [205]:
df = df.reindex(columns=['Location', 'Status', 'Transaction', 'Ownership', 'Furnishing', 'Facing', 'Overlooking_GardenPark', 'Overlooking_MainRoad', 'Overlooking_Pool', 'Overlooking_NotAvailable', 'Floor', 'TotalFloors', 'Bathroom', 'Balcony', 'CarParking', 'CarpetArea', 'Amount'])

In [208]:
df.dtypes

Location                     object
Status                       object
Transaction                  object
Ownership                    object
Furnishing                   object
Facing                       object
Overlooking_GardenPark        int64
Overlooking_MainRoad          int64
Overlooking_Pool              int64
Overlooking_NotAvailable      int64
Floor                       float64
TotalFloors                   int64
Bathroom                      int64
Balcony                       int64
CarParking                    int64
CarpetArea                  float64
Amount                      float64
dtype: object

### **Handling Outliers**

In [207]:
df.head()

,Location,Status,Transaction,Ownership,Furnishing,Facing,Overlooking_GardenPark,Overlooking_MainRoad,Overlooking_Pool,Overlooking_NotAvailable,Floor,TotalFloors,Bathroom,Balcony,CarParking,CarpetArea,Amount
0,Thane,Ready to Move,Resale,No data,Unfurnished,No data,0,0,0,1,0.909091,11,1,2,0,500.0,0.42
1,Thane,Ready to Move,Resale,Freehold,Semi-Furnished,East,1,0,0,0,0.136364,22,2,0,1,473.0,0.98
2,Thane,Ready to Move,Resale,Freehold,Unfurnished,East,1,0,0,0,0.344828,29,2,0,1,779.0,1.40
3,Thane,Ready to Move,Resale,No data,Unfurnished,No data,0,0,0,1,0.333333,3,1,1,0,530.0,0.25
4,Thane,Ready to Move,Resale,Co-operative Society,Unfurnished,West,1,1,0,0,0.476190,42,2,0,1,635.0,1.60